### ISSUE TITLE
miRNA mappings missing

### ISSUE THREAD

**Issue by DeniseSl22** [wikipathways/tool-wikipathways2wiki#2]
I believe miRNA IDs are modeled in Wikidata, but maybe your script isn't taking them into account?
It's not a topic in Scholia (yet) @egonw , so maybe it should be added there as well.
For the Wikidata properties, check: https://www.wikidata.org/wiki/Property_talk:P2870 , https://www.wikidata.org/wiki/Property:P2871 and https://www.wikidata.org/wiki/Property:P2870 (not sure which we are modeling in WPs, I think Susan/@khanspers might know :) .)

**Comment by Chris-Evelo** [comment]
miRNAs in WikiPathways are mostly meant as illustrations or to show that a particular, very important microRNA is the product of a specific gene. There are so many microRNAs related to any gene, let alone a pathway is so big that, we typically add them later using CyTargetLinker and one of the miRNA target databases (they often disagree, which is another reason to only add them dynamically). I would say that that makes it less important to be able to do mapping on the few that are in pathways, you will typically not use that for analysis. Besides, what would you map them too? Other IDs for the same thing? The initial preprocessed RNA? The gene itself? The latter two might create confusion since they also can give rise to other products. But of course, you will also need mappings that work with Cytoscape. Specific ones that work for specific questions. Indeed a good idea to talk to Susan and Kristina.

**Comment by khanspers** [comment]
Most miRNAs on WikiPathways are annotated with the gene ID (Ensembl), so won't work with the Wikidata properties which are both describing mirBase IDs that don't have Ensembl listed as external. I think our plan was to switch the existing miRNAs on pathways to mirBase IDs (MIMAT?) since that is more correct, but that hasn't happened yet.

**Comment by Chris-Evelo** [comment]
It also not trivial, right? A single Ensembl gene can give rise to multiple miRNAs.

**Comment by DeniseSl22** [comment]
@khanspers yes I believe the names of the Mi-RNAs are more descriptive now then some of the IDs (unfortunately).... So definitely something to think about for future PV releases @mkutmon . I don't believe the MirBase IDs have mappings in BridgeDb either, but if these are part of Wikidata that could perhaps be a separate mapping file in BridgeDb @egonw @fehrhart .

**Comment by mkutmon** [comment]
In PathVisio you can already add MIMAT identifiers if you want to. It's just that there are no mappings for those. I think we are switching back and worth with the identifiers for microRNAs - at some point we decided they should all be Ensembl, then back to MIMAT and so on. Mainly to facilitate analysis etc. 
So at this point, I am not sure what the best approach is. 
(1) You could see microRNAs similar to proteins (one gene can also result in different proteins and we still use the Ensembl identifiers for those) and keep the gene identifiers 
(2) we actually annotate the microRNAs with MIMAT and provide an additional mapping file (MIMAT->MI->gene) 
(3) every microRNA also has a link to a gene identifier in e.g. Ensembl (for that microRNA) which could be added to Wikidata (I assume)

**Comment by susancoort** [comment]
I think there are two issues here. 1) What is the meaning of the microRNA gene interaction in a pathway and 2) What type of data do you want to analyse using the pathways in which microRNAs are present. 
As far as I can see now most microRNA-gene interactions are interactions between mature microRNAs and their targets. Therefore I would annotate them with a MIMAT ID. If you want to include the expression of the microRNA gene you could add an additional gene box from which the mature microRNA originates. 
Many studies combine microRNA and gene expression data. The microRNA expression is annotated with MIMAT IDs or mature microRNA names. Of course, it could be relevant to include the expression of the microRNA gene, but then our pathways are misleading. From the gene, two mature microRNAs can be formed and they have different targets. 
Please note that you should also be careful with naming the microRNAs. mature microRNAs have a capital R (miR) in their name whereas the gene is with a lower case r (mir). This is not always used in the correct manner.
